# -*- coding: utf-8 -*-
"""Copy of PROJECT 108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1583bRjYJ2OuPg3Ia3Ui_rUnxZIhUd00T
"""

import csv
import plotly.express as px
import plotly.figure_factory as ff
import pandas as pd

df = pd.read_csv('/AMAZON.csv')
fig = ff.create_distplot([df['Avg Rating'].tolist()], ['Avg Rating'])
fig.show()